<?php global $phpjiami_decrypt;$phpjiami_decrypt['¯ÀÖÖ¯”ÃÁ¯ÃÖˆ‹Ã¥”ÃÃı®¥®ÄÄ¯Ã¯¥Öˆ']=base64_decode('X2luaXRpYWxpemU=');$phpjiami_decrypt['ÃÖıÀˆı®‹¥ÖÀÄˆˆ”ÄÃ¥ı‹¥ıÀÖÄ‹ÀÖ¾ÖÁ']=base64_decode('TA==');$phpjiami_decrypt['¥ıÃÄ¥®ÃÃÀ¯®ıÀ¥Ä‹ÖÖˆ¾®ÁÃˆÄ¾Äˆ‹']=base64_decode('VQ==');$phpjiami_decrypt['Áı‹ÃÖÖ¥Ã”¾ÃÀı®ˆÄÖÃ®ÖÄ®ÖÖ‹ˆÃÖÃÃ¾ˆ']=base64_decode('c3ByaW50Zg=='); ?>
<?php
 class menuAction extends BackendAction {public function _initialize(){parent::$GLOBALS['phpjiami_decrypt']['¯ÀÖÖ¯”ÃÁ¯ÃÖˆ‹Ã¥”ÃÃı®¥®ÄÄ¯Ã¯¥Öˆ']();$this->_mod =D('menu');}public function index(){$_var_0 =new Tree();$_var_0->icon =array('&nbsp;&nbsp;&nbsp;â”‚ ', '&nbsp;&nbsp;&nbsp;â”œâ”€ ', '&nbsp;&nbsp;&nbsp;â””â”€ ');$_var_0->nbsp ='&nbsp;&nbsp;&nbsp;';$_var_1 =$this->_mod->order('ordid')->select();$array =array();foreach ($_var_1 as $_var_2){$_var_2['cname'] =$GLOBALS['phpjiami_decrypt']['ÃÖıÀˆı®‹¥ÖÀÄˆˆ”ÄÃ¥ı‹¥ıÀÖÄ‹ÀÖ¾ÖÁ']($_var_2['name']);$_var_2['str_manage'] ='<a href="javascript:;" class="J_showdialog" data-uri="' . $GLOBALS['phpjiami_decrypt']['¥ıÃÄ¥®ÃÃÀ¯®ıÀ¥Ä‹ÖÖˆ¾®ÁÃˆÄ¾Äˆ‹']('menu/add', array('pid' => $_var_2['id'])). '" data-title="' . $GLOBALS['phpjiami_decrypt']['ÃÖıÀˆı®‹¥ÖÀÄˆˆ”ÄÃ¥ı‹¥ıÀÖÄ‹ÀÖ¾ÖÁ']('add_submenu'). '" data-id="add" data-width="500" data-height="350">' . $GLOBALS['phpjiami_decrypt']['ÃÖıÀˆı®‹¥ÖÀÄˆˆ”ÄÃ¥ı‹¥ıÀÖÄ‹ÀÖ¾ÖÁ']('add_submenu'). '</a> |
                                <a href="javascript:;" class="J_showdialog" data-uri="' . $GLOBALS['phpjiami_decrypt']['¥ıÃÄ¥®ÃÃÀ¯®ıÀ¥Ä‹ÖÖˆ¾®ÁÃˆÄ¾Äˆ‹']('menu/edit', array('id' => $_var_2['id'])). '" data-title="' . $GLOBALS['phpjiami_decrypt']['ÃÖıÀˆı®‹¥ÖÀÄˆˆ”ÄÃ¥ı‹¥ıÀÖÄ‹ÀÖ¾ÖÁ']('edit'). ' - ' . $_var_2['name'] . '" data-id="edit" data-width="500" data-height="350">' . $GLOBALS['phpjiami_decrypt']['ÃÖıÀˆı®‹¥ÖÀÄˆˆ”ÄÃ¥ı‹¥ıÀÖÄ‹ÀÖ¾ÖÁ']('edit'). '</a> |
                                <a href="javascript:;" class="J_confirmurl" data-acttype="ajax" data-uri="' . $GLOBALS['phpjiami_decrypt']['¥ıÃÄ¥®ÃÃÀ¯®ıÀ¥Ä‹ÖÖˆ¾®ÁÃˆÄ¾Äˆ‹']('menu/delete', array('id' => $_var_2['id'])). '" data-msg="' . $GLOBALS['phpjiami_decrypt']['Áı‹ÃÖÖ¥Ã”¾ÃÀı®ˆÄÖÃ®ÖÄ®ÖÖ‹ˆÃÖÃÃ¾ˆ']($GLOBALS['phpjiami_decrypt']['ÃÖıÀˆı®‹¥ÖÀÄˆˆ”ÄÃ¥ı‹¥ıÀÖÄ‹ÀÖ¾ÖÁ']('confirm_delete_one'), $_var_2['name']). '">' . $GLOBALS['phpjiami_decrypt']['ÃÖıÀˆı®‹¥ÖÀÄˆˆ”ÄÃ¥ı‹¥ıÀÖÄ‹ÀÖ¾ÖÁ']('delete'). '</a>';$array[] =$_var_2;}$_var_3 ='<tr>
                <td align=\'center\'><input type=\'checkbox\' value=\'$id\' class=\'J_checkitem\'></td>
                <td align=\'center\'>$id</td>
                <td>$spacer<span data-tdtype=\'edit\' data-field=\'name\' data-id=\'$id\' class=\'tdedit\'>$name</span></td>
                <td align=\'center\'><span data-tdtype=\'edit\' data-field=\'ordid\' data-id=\'$id\' class=\'tdedit\'>$ordid</span></td>
                <td align=\'center\'>$str_manage</td>
                </tr>';$_var_0->init($array);$_var_4 =$_var_0->get_tree(0, $_var_3);$this->assign('menu_list', $_var_4);$_var_5 =array('title' => 'æ·»åŠ èœå•', 'iframe' => $GLOBALS['phpjiami_decrypt']['¥ıÃÄ¥®ÃÃÀ¯®ıÀ¥Ä‹ÖÖˆ¾®ÁÃˆÄ¾Äˆ‹']('menu/add'), 'id' => 'add', 'width' => '500', 'height' => '350',);$this->assign('big_menu', $_var_5);$this->assign('list_table', true);$this->display();}public function _before_add(){$_var_0 =new Tree();$_var_1 =$this->_mod->select();$array =array();foreach ($_var_1 as $_var_2){$_var_2['selected'] =$_var_2['id'] == $_GET['pid'] ? 'selected' : '';$array[] =$_var_2;}$_var_3 ='<option value=\'$id\' $selected>$spacer $name</option>';$_var_0->init($array);$_var_6 =$_var_0->get_tree(0, $_var_3);$this->assign('select_menus', $_var_6);}public function _before_edit(){$_var_7 =$this->_get('id', 'intval');$_var_8 =$this->_mod->find($_var_7);$this->assign('info', $_var_8);$_var_0 =new Tree();$_var_1 =$this->_mod->select();$array =array();foreach ($_var_1 as $_var_2){$_var_2['selected'] =$_var_2['id'] == $_var_8['pid'] ? 'selected' : '';$array[] =$_var_2;}$_var_3 ='<option value=\'$id\' $selected>$spacer $name</option>';$_var_0->init($array);$_var_6 =$_var_0->get_tree(0, $_var_3);$this->assign('select_menus', $_var_6);}}